defaults:
  - default
  - data: kitti_raw
  - model_conf/backbone: default
  - _self_

name: "kitti_raw"
model: "vipocc"
output_path: out/${name}

num_epochs: 50
batch_size: 16
#visualize_every: 10
#validate_every: 20
checkpoint_every: 500


save_best:
  metric: abs_rel
  sign: -1
  n_saved: 10

data:
  data_fc: 2
  image_size: [ 192, 640 ]
  color_aug: true
  return_pseudo_depth: true

model_conf:
  arch: "BTSNet"
  use_code: true
  prediction_mode: default

  code:
    num_freqs: 6
    freq_factor: 1.5
    include_input: true

  backbone:
    use_depth_branch: true

  mlp_coarse:
    type: "resnet"
    n_blocks: 0
    d_hidden: 64

  mlp_fine:
    type: "empty"
    n_blocks: 1
    d_hidden: 128

  z_near: 3
  z_far: 80
  inv_z: true

  n_frames_encoder: 1
  n_frames_render: 2
  frame_sample_mode: default

  sample_mode: patch
  patch_size: 8
  ray_batch_size: 2048

  flip_augmentation: true

  learn_empty: false
  code_mode: z

loss:
  criterion: "l1+ssim"
  invalid_policy: weight_guided
  lambda_depth_supervision: 0.0
  lambda_depth_recon: 0.0
  lambda_temporal_alignment: 0.0

scheduler:
  type: step
  step_size: 120000
  gamma: 0.1

renderer:
  n_coarse: 64
  n_fine: 0
  n_fine_depth: 0
  depth_std: 1.0
  sched: [ ]
  white_bkgd: false
  lindisp: true
  hard_alpha_cap: true
